/* eslint-disable */
// This file is normally generated by the TanStack Router plugin. It is checked in
// so the starter renders before the first generator run in constrained environments.
import { rootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';
import { Route as AppRoute } from './routes/app';
import { Route as PricingRoute } from './routes/pricing';

const Index = IndexRoute.update({ id: '/', path: '/', getParentRoute: () => rootRoute } as any);
const App = AppRoute.update({ id: '/app', path: '/app', getParentRoute: () => rootRoute } as any);
const Pricing = PricingRoute.update({ id: '/pricing', path: '/pricing', getParentRoute: () => rootRoute } as any);

export const routeTree = rootRoute.addChildren([Index, App, Pricing]);
